---
- name: Install and configure LEMP server
  hosts: all
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      tags: [common]

    - name: Install required packages
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - nginx
          - mysql-server
          - php-fpm
          - php-mysql
          - php-curl
          - php-gd
          - php-mbstring
          - php-xml
          - unzip
          - php8.1-fpm
      tags: [common]

    - name: Start and enable services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - nginx
        - mysql
        - php8.1-fpm
      tags: [common]

    - name: Configure Nginx
      template:
        src: templates/nginx-domain
        dest: /etc/nginx/sites-available/default
      notify:
        - Restart Nginx
      tags: [nginx]

    - name: Create MySQL database
      mysql_db:
        name: wordpress
        state: present
      tags: [mysql]

    - name: Create MySQL user
      mysql_user:
        name: wordpress_user
        password: $WORDPRESS_PASSWORD
        priv: 'wordpress.*:ALL'
        host: localhost
        state: present
      tags: [mysql]

    - name: Download WordPress
      get_url:
        url: "https://wordpress.org/latest.tar.gz"
        dest: /tmp/wordpress.tar.gz
      tags: [wordpress]

    - name: Extract WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/
        remote_src: yes
        owner: www-data
        group: www-data
      tags: [wordpress]

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
