heat_template_version: rocky

description: >
  Deploys a devstack controller to the DMZ and private networks

parameters:
  server_name:
    type: string
    default: devstack-controller
  key_name:
    type: string
    default: devstack-controller
  image:
    type: string
    default: Ubuntu 22.04 (Jammy)
  flavor:
    type: string
    default: alt.st1.small
  external_network_id:
    type: string
    default: External
  dmz_network_id:
    type: string
    default: dmz_network
  dmz_subnet_id:
    type: string
    default: dmz_subnet1
  private_network_id:
    type: string
    default: private_network
  private_subnet_id:
    type: string
    default: private_subnet1
  security_groups: 
    type: comma_delimited_list 
    default: 
      - "ssh-ingress"
      - "default"
  ssh_pubkey:
    type: string
    # default: { get_file: ../pubkeys/devstack-controller.pub }
    default: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDENOQD1rBSkoWOboawEExl6FtoqBEs2Oux0Sd0SQ/cglKUtDiTLCfsxbxdAx72JQDH7EKq/4iOze+larFjN0Wrs95Dl41G+9Jh2+gnPQTHyuQXumPIk98QWUl4w6Y3jiP2iFClKl2LkCh6XA4nh4jvwTMvlRJT1DoswfWYmyH+jUmq329062ti7qvKBQNEON5KwFpwM37TTS/pP6/cpoVXiLKYq+s8rHxVoXjp7EA0un/4SDmycE77SPkHtaL1L2RAYvURaCMl/19hOPCKBtHsIt/OsHQKoxSyhH+3sKI3G4ld9yRYKRWWo4TZCSl35DTM0Wii8LDL0JKnlP64nhoZgK2JoWd8cI3GAVpZSnTfF96LmAjZGiI2+7ZTDkKbkIBeMNaRwDbO5KXrn/02TWGYq7E1QwH7nUwAIz7zp4v8fqohwqr/esLdSuXgmLt9db1xj/AT/UoKZwZ/COHW7IIr1bCYZcvy3nD0PZecK9hZ1aUc46sug4RO7OtVIOQ13kqtYnfRuq7IJl5UbtTibPuhy5/5vMg//3YlEKL1Iy1aQKkGLKUrbYGhbx7bX8Ruqb0nYB9qGhLXmr917MNPKurdoBlom12XcVNk2UbzLxJV2STEKZeo7DWc/ku5Xe6iFaLOaNnif17O4SN321ZkoJ5tfdBMq4ME/OuXNUYQArtr2Q==

resources:
  server:
    type: OS::Nova::Server
    properties:
      name: { get_param: server_name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: server_private_port }
        - port: { get_resource: server_dmz_port }
      user_data_format: RAW
      user_data: { get_resource: server_init }
      
  server_dmz_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: dmz_network_id }
      fixed_ips:
        - subnet_id: { get_param : dmz_subnet_id }
      security_groups: # TODO stop hardcoding these and do it correctly
        - default
        - ssh-ingress

  server_private_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: private_network_id }
      fixed_ips:
        - subnet_id: { get_param : private_subnet_id }
      security_groups:
        - default
        - ssh-ingress
  
  server_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: external_network_id }
      port_id: { get_resource: server_dmz_port }

  server_init:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        #cloud-config
        users:
          - name: drew
            sudo: ['ALL=(ALL) NOPASSWD:ALL']
            groups: sudo
            shell: /bin/bash
            ssh-authorized-keys:
              - { get_param: ssh_pubkey }
          - name: stack
            sudo: ['ALL=(ALL) NOPASSWD:ALL']
            shell: /bin/bash
        write_files:
          - content: { get_file: template_resources/etc_network_interfaces.txt }
            path: /etc/network/interfaces
            permission: 0755
          - content: { get_file: template_resources/devstack_controller_local.conf }
            path: /home/stack/local.conf
            owner: stack:stack
            permission: 0755
        runcmd:
          - sudo sed -i'' -e "s/[\#]*Port\s.*/Port 1355/" /etc/ssh/sshd_config
          - sudo sed -i'' -e 's/[\#]*PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config
          - sudo sed -i'' -e '$aAllowUsers drew' /etc/ssh/sshd_config
          - sudo systemctl restart ssh
          - git clone https://opendev.org/openstack/devstack /home/stack/devstack
          - cp /home/stack/local.conf /home/stack/devstack/local.conf
          - chown stack:stack -R /home/stack
          - cd /home/stack/devstack
          - sudo su stack -c ./stack.sh

outputs:
  server_external_ip:
    description: public IP address of the deployed compute instance
    value: { get_attr: [server_floating_ip, floating_ip_address] }
  server_dmz_ip:
    description: private IP address on the dmz_network
    value: { get_attr: [server, networks, dmz_network, 0] }
  server_private_ip:
    description: private IP address on an private_network network only accessible through the firewall
    value: { get_attr: [server, networks, private_network, 0] }