services:
  protonmail-bridge-init:
    container_name: protonmail-bridge
    stdin_open: true
    tty: true
    volumes:
        - protonmail:/root
    image: shenxn/protonmail-bridge
    command: init

  protonmail-bridge:
    container_name: protonmail-bridge
    volumes:
      - protonmail:/root
    ports:
      - 1025:25/tcp
      - 1143:143/tcp
    restart: unless-stopped
    image: shenxn/protonmail-bridge

volumes:
    protonmail: {}