version: "3.9"
services:
  wordpress:
    container_name: wordpress
    image: wordpress:php8.2-apache
    restart: always
    stdin_open: true
    tty: true
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: Ch4ngeM3N0w!
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html

  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: Ch4ngeM3N0w!
      MYSQL_RANDOM_ROOT_PASSWORD: 'root_pass'
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/ssl:/etc/nginx/ssl
      - wordpress_data:/var/www/html
    environment:
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".template"
      DOMAIN: ${DOMAIN}

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/var/www/html --email youremail@domain.com --agree-tos --no-eff-email -d ${DOMAIN}
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
      - ./certbot/logs:/var/log/letsencrypt
      - wordpress_data:/var/www/html
    depends_on:
      - nginx
    environment:
      DOMAIN: ${DOMAIN}

volumes:
  db_data:
  wordpress_data:
