version: "3.9"
services:
  wordpress:
    container_name: wordpress
    image: wordpress:php8.2-apache
    restart: always
    stdin_open: true
    tty: true
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: Ch4ngeM3N0w!
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html

  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: Ch4ngeM3N0w!
      MYSQL_RANDOM_ROOT_PASSWORD: 'root_pass'
    volumes:
      - db_data:/var/lib/mysql

  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Eastern
      - URL=${DOMAIN}
      - VALIDATION=http
      # - SUBDOMAINS=${SUBDOMAIN} #optional
      - EMAIL= #optional
      - ONLY_SUBDOMAINS=false #optional
      - EXTRA_DOMAINS= #optional
      - STAGING=${STAGING} #optional
    volumes:
      - ./swag:/config
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443

volumes:
  db_data:
  wordpress_data:
