version: "3.9"
services:
  wordpress:
    container_name: wordpress
    image: wordpress:latest
    restart: always
    stdin_open: true
    tty: true
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define( 'AUTOMATIC_UPDATER_DISABLED', false );
        define( 'WP_AUTO_UPDATE_CORE', true );
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wordpress_network
    healthcheck:
      test: "curl --fail http://localhost:80"
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3

  wp-cli:
    container_name: wp-cli
    image: wordpress:cli
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
      - /config/wordpress/plugins:/config/wordpress/plugins
    networks:
      - wordpress_network

  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_network

  traefik:
    image: traefik:latest
    container_name: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/traefik/traefik.yaml:/etc/traefik/traefik.yaml
      - /etc/traefik/routes.yaml:/etc/traefik/routes.yaml
      - /etc/traefik/acme.json:/acme.json
      - /etc/traefik/certs:/etc/traefik/certs
    # network_mode: host
    networks: 
      - wordpress_network
    environment:
      - URL=${URL}
    ports:
      - 80:80
      - 443:443
    labels:
      traefik.http.services.traefik-dashboard-service.loadbalancer.server.port: 9999
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8080"]
    #   interval: 1m30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 2m

volumes:
  db_data:
  wordpress_data:

networks:
  wordpress_network: