http:
  routers:
    router:
      rule: Host(`{{ env "URL" }}`) && PathPrefix(`{root:/.*}`)
      service: service
      entryPoints:
        - websecure
        - web
      tls: {}
  services:
    service:
      loadBalancer:
        servers:
          - url: http://wordpress:80
