---
version: "2.1"
services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      # - PLEX_CLAIM= #optional
    volumes:
      - /mnt/blackbox/media/tv:/tv
      - /mnt/blackbox/media/movies:/movies
    restart: unless-stopped