http:
  routers:
    router:
      rule: Host(``) && PathPrefix(`/`)
      service: service
      entryPoints:
        - websecure
      tls: 
        certResolver: letsencrypt-prod

  services:
    service:
      loadBalancer:
        servers:
          - url: http://openproject-proxy-1:80
