heat_template_version: rocky

description: >
  Simple single node jump server template

parameters:
  key_name:
    type: string
    description: Name of keypair to assign to servers
    default: dr_ew
  image:
    type: string
    description: Name of image to use for servers
    # default: 5557a492-f9f9-4a8a-98ec-5f642b611d23 # Ubuntu 22.04
    default: d2978bb6-6326-40e5-b9e4-ebc956599c09 # IPFire Linux
  flavor:
    type: string
    description: Flavor to use for servers
    default: alt.st1.small
  external_network_id:
    type: string
    description: ID of public network for which floating IP addresses will be allocated
    default: External
  external_subnet_id:
    type: string
    default: Internet_d85720c0 # 4e7309a5-50d3-46f1-bf37-2f2af80e3130
  private_network_id:
    type: string
    description: ID of private network into which servers get deployed
    default: private_network
  private_subnet_id:
    type: string
    description: ID of private sub network into which servers get deployed
    default: private_subnet1
  dmz_network_id:
    type: string
    default: dmz_network
  dmz_subnet_id:
    type: string
    default: dmz_subnet1
  security_groups: 
    type: comma_delimited_list 
    default: [ "default", "ssh-ingress" ]
  ssh_port:
    type: number
    default: 1355
  new_user_name:
    type: string
    default: drew
  ssh_pubkey:
    type: string
    default: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDPNG6afWDqOCptAg2ERApA42HX7VG7Nw1hLjuCYpb8Ij36A0F/OUxDpA1O/+EKibLL+MgpwMzC3J5a+8ifkRH3Cr/OwOeiq/lcHgiC3rJcLr8kyNLwQmpYhSZkQMR0m2Y850Okix5dmNlK8KcE5RwG3q04DY0W09Rx/LWlUm1Z0ipkJ4NECDWTRKEoelJ72YREB1j9awJFBKLn2Ip8lylK7lrZu1Q64mOib551HYOr2xCLdTUoUI9pReesBVYKdVinsyyjuZ5HAxb8SOEdGA+8AGLhfoBdcQ7zNHfGmOrCtTsZqL1y/HQM4EimhBBUdT7tnJzWitTlx4bA7qo+cZ5bX5Zy+VR1rFpUit2xzU+1jImExnK3ltDAPec6qMDrK9wOFwJna5WKTKtEEStRNiv0yNDElrvSMu2srriORH9HwINOnSOuWDiYldlTJnLW8P4h0EBf8hw2ZKy4YOopDEuStthli6QlVKYji1qNMh2kKiuxAmWv6nzG9KrZJl/nohehtaXYYsXNk5jl3AOYnrC6xgLDcyHd1II78G+lujvUl0EJPmnYQA7rJVqem2I516ixTBaVR5htXvPclLXl+kmmOwtltNCRqPXaWB/9e3LFyZuO7A/r4UEC16v9t0OnEHvjRJ6dLQey+hnJN398egXAQmXjSXVJgNejsxCz7uUzSw== doctor_ew@Tiffanys-Air

resources:
  firewall:
    type: OS::Nova::Server
    properties:
      name: firewall
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: firewall_port_private }
        - port: { get_resource: firewall_port_dmz }

  firewall_port_private:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: private_network_id }
      fixed_ips:
        - subnet_id: { get_param: private_subnet_id }
      security_groups:
        - default
        - ssh-ingress
        - ipfire-web-ui

  firewall_port_dmz:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: dmz_network_id }
      fixed_ips:
        - subnet_id: { get_param: dmz_subnet_id }
      security_groups:
        - default
        - ssh-ingress

  firewall_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: external_network_id }
      port_id: { get_resource: firewall_port_dmz }

outputs:
  firewall_external_ip:
    description: IP address of the deployed compute instance
    value: { get_attr: [firewall_floating_ip, floating_ip_address] }
  firewall_private_ip:
    description: Private IP address of the deployed compute instance
    value: { get_attr: [firewall, networks, private_network, 0] }
  firewall_dmz_ip:
    description: Private IP address of the deployed compute instance
    value: { get_attr: [firewall, networks, dmz_network, 0] }