heat_template_version: rocky

description: >
  Public facing SSH server with connection to internal network

parameters:
  key_name:
    type: string
    default: jump-server
  image:
    type: string
    default: Ubuntu 22.04 (Jammy)
  flavor:
    type: string
    default: alt.st1.small
  external_network_id:
    type: string
    default: External
  dmz_network_id:
    type: string
    default: dmz_network
  dmz_subnet_id:
    type: string
    default: dmz_subnet1
  private_network_id:
    type: string
    default: private_network
  private_subnet_id:
    type: string
    default: private_subnet1
  security_groups: 
    type: comma_delimited_list 
    default: 
      - "ssh-ingress"
      - "default"
  ssh_pubkey:
    type: string
    # default: { get_file: ../pubkeys/jump-server.pub }
    default: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCqaVA8bI1dzmTnTz39JCbihcYi8K7r43bIID5XwpxkMLaR0Ce/TT6aaRC8qEzoeBdjqiH+LG97+EIsaUOlXDs/GdHbDkW3ZtLGoJByfyz/sAQP5ySTC1kqik369Gjm19LzSlhWf9roem5RSNRPo49mrP2nwt9ffw8rp9iLLwdm6ZUJxRy9OG+UBayY3gq9ixYKf1wZSY320WKf077xX6JgroUheA399Jm7KRewhpNvpoawRXl/CggFK8jL6Wb4F5jZWMfnIziUEhFMxl6aueeQzk+Daa0Wg2Y9oBjgYUM/RW/rItowo5gD89wJwDygWw1F/Y0SGrLnlCbWJSHy8lm1+2J9Bs0oHSL/xZXKW4iVhB30jcCsbdKskX8X2JeLgX+fQChdl6cOKP+ZedKNzeHBq9i0a7R+YtI+1LUaA75lSIxqlba37Z6pocmUtnyal8nJd9kG/v6/BIkltDTa33kLXImBkfnGP+HEmQb41dUwb4Wei8QxI75Bg9+H3m1nY1lWcZSnhk0z5r6YuPONsqiQBDhoZvqzE1YctUNleUgVCRK4GWVTNJueuyRpVvP2eqPyZjzOZrdRZK1k2AJzjjHlfj86RY7kVeRbON3HfFOZf0PFOtABaOrlKeOmDoXSl5YE7UaUQAwTFCZmUXNkFnysa7VHTNWs3Lka+44dhJCHtw==

resources:
  jump_server:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: jump_server_private_port }
        - port: { get_resource: jump_server_dmz_port }
      user_data_format: RAW
      user_data: { get_resource: jump_server_init }
      
  jump_server_dmz_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: dmz_network_id }
      fixed_ips:
        - subnet_id: { get_param : dmz_subnet_id }
      security_groups: # TODO stop hardcoding these and do it correctly
        - default
        - ssh-ingress

  jump_server_private_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: private_network_id }
      fixed_ips:
        - subnet_id: { get_param : private_subnet_id }
      security_groups:
        - default
        - ssh-ingress
  
  jump_server_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: external_network_id }
      port_id: { get_resource: jump_server_dmz_port }

  jump_server_init:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        #cloud-config
        users:
          - name: drew
            sudo: ['ALL=(ALL) NOPASSWD:ALL']
            groups: sudo
            shell: /bin/bash
            ssh-authorized-keys:
              - { get_param: ssh_pubkey }
        runcmd:
          - sudo sed -i'' -e "s/[\#]*Port\s.*/Port 1355/" /etc/ssh/sshd_config
          - sudo sed -i'' -e 's/[\#]*PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config
          - sudo sed -i'' -e '$aAllowUsers drew' /etc/ssh/sshd_config
          - sudo systemctl restart ssh

outputs:
  jump_server_external_ip:
    description: public IP address of the deployed compute instance
    value: { get_attr: [jump_server_floating_ip, floating_ip_address] }
  jump_server_dmz_ip:
    description: private IP address on the dmz_network
    value: { get_attr: [jump_server, networks, dmz_network, 0] }
  jump_server_private_ip:
    description: private IP address on an private_network network only accessible through the firewall
    value: { get_attr: [jump_server, networks, private_network, 0] }