heat_template_version: rocky

description: >
  Public facing SSH server with connection to internal network

parameters:
  key_name:
    type: string
    description: Name of keypair to assign to servers
    default: jump-server
  image:
    type: string
    description: Name of image to use for servers
    default: Ubuntu 22.04 (Jammy)
  flavor:
    type: string
    description: Flavor to use for servers
    default: alt.st1.small
  external_network_id:
    type: string
    description: ID of public network for which floating IP addresses will be allocated
    default: External
  dmz_network_id:
    type: string
    default: dmz_network
  dmz_subnet_id:
    type: string
    default: dmz_subnet1
  private_network_id:
    type: string
    default: private_network
  private_subnet_id:
    type: string
    default: private_subnet1
  security_groups: 
    type: comma_delimited_list 
    default: 
      - "ssh-ingress"
      - "default"
  ssh_pubkey:
    type: string
    default: { get_file: ../pubkeys/jump-server.pub }

resources:
  jump_server:
    type: OS::Nova::Server
    properties:
      name: jump_server
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: jump_server_private_port }
        - port: { get_resource: jump_server_dmz_port }
      user_data_format: RAW
      user_data: { get_resource: jump_server_init }
      
  jump_server_dmz_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: dmz_network_id }
      fixed_ips:
        - subnet_id: { get_param : dmz_subnet_id }
      security_groups: # TODO stop hardcoding these and do it correctly
        - default
        - ssh-ingress

  jump_server_private_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: private_network_id }
      fixed_ips:
        - subnet_id: { get_param : private_subnet_id }
      security_groups:
        - default
        - ssh-ingress
  
  jump_server_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: external_network_id }
      port_id: { get_resource: jump_server_dmz_port }

  jump_server_init:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        #cloud-config
        users:
          - name: drew
            sudo: ['ALL=(ALL) NOPASSWD:ALL']
            groups: sudo
            shell: /bin/bash
            ssh-authorized-keys:
              - { get_param: ssh_pubkey }
        runcmd:
          - sudo sed -i'' -e "s/[\#]*Port\s.*/Port 1355/" /etc/ssh/sshd_config
          - sudo sed -i'' -e 's/[\#]*PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config
          - sudo sed -i'' -e '$aAllowUsers drew' /etc/ssh/sshd_config
          - sudo systemctl restart ssh

outputs:
  jump_server_external_ip:
    description: public IP address of the deployed compute instance
    value: { get_attr: [jump_server_floating_ip, floating_ip_address] }
  jump_server_dmz_ip:
    description: private IP address on the dmz_network
    value: { get_attr: [jump_server, networks, dmz_network, 0] }
  jump_server_private_ip:
    description: private IP address on an private_network network only accessible through the firewall
    value: { get_attr: [jump_server, networks, private_network, 0] }