heat_template_version: rocky

description: Public internet facing SSH point to access resources behind the firewall
parameters:
  key_name:
    type: string
    description: Name of keypair to assign to servers
    default: jump-server
  image:
    type: string
    description: Name of image to use for servers
    default: Ubuntu 22.04 (Jammy)
  flavor:
    type: string
    description: Flavor to use for servers
    default: alt.st1.small
  public_network_id:
    type: string
    description: ID of public network for which floating IP addresses will be allocated
    default: External
  floating_network_id:
    type: string
    default: wordpress
  floating_subnet_id:
    type: string
    default: fdf094e8-d4ee-48d0-8952-92b4db4218d1
  security_groups: 
    type: comma_delimited_list 
    default: 
      - "ssh-ingress"
      - "default"
  ssh_pubkey:
    type: string
    default: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCqaVA8bI1dzmTnTz39JCbihcYi8K7r43bIID5XwpxkMLaR0Ce/TT6aaRC8qEzoeBdjqiH+LG97+EIsaUOlXDs/GdHbDkW3ZtLGoJByfyz/sAQP5ySTC1kqik369Gjm19LzSlhWf9roem5RSNRPo49mrP2nwt9ffw8rp9iLLwdm6ZUJxRy9OG+UBayY3gq9ixYKf1wZSY320WKf077xX6JgroUheA399Jm7KRewhpNvpoawRXl/CggFK8jL6Wb4F5jZWMfnIziUEhFMxl6aueeQzk+Daa0Wg2Y9oBjgYUM/RW/rItowo5gD89wJwDygWw1F/Y0SGrLnlCbWJSHy8lm1+2J9Bs0oHSL/xZXKW4iVhB30jcCsbdKskX8X2JeLgX+fQChdl6cOKP+ZedKNzeHBq9i0a7R+YtI+1LUaA75lSIxqlba37Z6pocmUtnyal8nJd9kG/v6/BIkltDTa33kLXImBkfnGP+HEmQb41dUwb4Wei8QxI75Bg9+H3m1nY1lWcZSnhk0z5r6YuPONsqiQBDhoZvqzE1YctUNleUgVCRK4GWVTNJueuyRpVvP2eqPyZjzOZrdRZK1k2AJzjjHlfj86RY7kVeRbON3HfFOZf0PFOtABaOrlKeOmDoXSl5YE7UaUQAwTFCZmUXNkFnysa7VHTNWs3Lka+44dhJCHtw==

resources:
  server:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
      - port: { get_resource: server_public_port }
      user_data_format: RAW
      user_data: { get_resource: server_init }

  server_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_network_id }
      port_id: { get_resource: server_public_port }

  server_public_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: floating_network_id }
      fixed_ips:
        - subnet_id: { get_param: floating_subnet_id }
      security_groups:
        - "default"
        - "ssh-ingress"

  server_init:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        #cloud-config
        users:
          - name: drew
            sudo: ['ALL=(ALL) NOPASSWD:ALL']
            groups: sudo
            shell: /bin/bash
            ssh-authorized-keys:
             - { get_param: ssh_pubkey }
        write_files:
          - content: { get_file: ../scripts/setup-ssh.sh }
            owner: root:root
            permissions: '700'
            path: /etc/setup-ssh.sh
          - content: { get_file: ../scripts/setup-k8s-clients.sh }
            owner: drew:drew
            permissions: '700'
            path: /etc/setup-k8s-clients.sh
        runcmd:
          - apt update
          - apt install -y bash-completion
          - bash -c /etc/setup-ssh.sh
          - sed -i'' -e 's/[#$]+nrconf{restart} = .*/\$nrconf{restart} = "a"/' /etc/needrestart/needrestart.conf
          - chown drew:drew -R /home/drew

outputs:
  server_public_ip:
    description: public IP address of the deployed compute instance
    value: { get_attr: [server_floating_ip, floating_ip_address] }
  server_dmz_ip:
    description: private IP address on the dmz_network
    value: { get_attr: [server, networks, dmz_network, 0] }