heat_template_version: rocky

description: >
  Single instance WordPress server

parameters:
  key_name:
    type: string
    description: Name of keypair to assign to servers
    default: jump-server
  image:
    type: string
    description: Name of image to use for servers
    default: Ubuntu 22.04 (Jammy)
  flavor:
    type: string
    description: Flavor to use for servers
    default: alt.st1.small
  public_network_id:
    type: string
    description: ID of public network for which floating IP addresses will be allocated
    default: External
  private_network_id:
    type: string
    description: ID of private network into which servers get deployed
    default: private_network
  private_subnet_id:
    type: string
    description: ID of private sub network into which servers get deployed
    default: private_subnet1 # private's only subnet
  floating_network_id:
    type: string
    default: dmz_network
  floating_subnet_id:
    type: string
    default: dmz_subnet1
  security_groups: 
    type: comma_delimited_list 
    default: 
      - "ssh-ingress"
      - "default"
  ssh_pubkey:
    type: string
    default: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCqaVA8bI1dzmTnTz39JCbihcYi8K7r43bIID5XwpxkMLaR0Ce/TT6aaRC8qEzoeBdjqiH+LG97+EIsaUOlXDs/GdHbDkW3ZtLGoJByfyz/sAQP5ySTC1kqik369Gjm19LzSlhWf9roem5RSNRPo49mrP2nwt9ffw8rp9iLLwdm6ZUJxRy9OG+UBayY3gq9ixYKf1wZSY320WKf077xX6JgroUheA399Jm7KRewhpNvpoawRXl/CggFK8jL6Wb4F5jZWMfnIziUEhFMxl6aueeQzk+Daa0Wg2Y9oBjgYUM/RW/rItowo5gD89wJwDygWw1F/Y0SGrLnlCbWJSHy8lm1+2J9Bs0oHSL/xZXKW4iVhB30jcCsbdKskX8X2JeLgX+fQChdl6cOKP+ZedKNzeHBq9i0a7R+YtI+1LUaA75lSIxqlba37Z6pocmUtnyal8nJd9kG/v6/BIkltDTa33kLXImBkfnGP+HEmQb41dUwb4Wei8QxI75Bg9+H3m1nY1lWcZSnhk0z5r6YuPONsqiQBDhoZvqzE1YctUNleUgVCRK4GWVTNJueuyRpVvP2eqPyZjzOZrdRZK1k2AJzjjHlfj86RY7kVeRbON3HfFOZf0PFOtABaOrlKeOmDoXSl5YE7UaUQAwTFCZmUXNkFnysa7VHTNWs3Lka+44dhJCHtw==

resources:
  server:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
      - port: { get_resource: server_private_port }
      - port: { get_resource: server_public_port }
      user_data_format: RAW
      user_data: { get_resource: server_init }

  server_private_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: private_network_id }
      fixed_ips:
        - subnet_id: { get_param: private_subnet_id }
      security_groups: #{ get_param: security_groups } #[{ get_resource: server_security_group }]
        - "default"
        - "ssh-ingress"

  server_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_network_id }
      port_id: { get_resource: server_public_port }

  server_public_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: floating_network_id }
      fixed_ips:
        - subnet_id: { get_param: floating_subnet_id }
      security_groups: #{ get_param: security_groups } #[{ get_resource: server_security_group }]
        - "default"
        - "ssh-ingress"

  server_init:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        #cloud-config
        users:
          - name: drew
            sudo: ["ALL=(ALL) NOPASSWD:ALL"]
            groups: sudo
            shell: /bin/bash
            # passwd: asdfasdf
            # lock-password: false
            # ssh_pwauth: True
            # chpasswd: { expire: False }
            ssh-authorized-keys:
              - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDFiGac2S5x4ebgapffpQqhhHFyS7G7QuOTH7szruWsEJ//xTAfOcVdyPjyv/mDG7q6Rj4Z1+XdJoM8QtVjNMEHxUcTCe+YrGQsJJJzxp30uSTEKCBBSjq5mz5E7oRTus1nojJb02cPiP+0iHbTvBoscY/3qKL2H/xjdE1TBRXr3KZIEiuY4RzSgtFe/9H8txANU/UkxXU8wq85jxFXybvn3Ln/puGAcoPGAm6VBTdcMlbH4wXGB6QHMyTnbI+f+m7Sd1K3RQVvZyvipNbtyPORsfDofW+lJj4rNxsZDPRDpDtWYGXsTMVwrORS44CKc7ozjOj3gc7W60qBb8dkJVaS6Bv+jeGTAwp7nKHehSmpCdXd+wKGDHVo39E190kyLLVTQ1F94RzxBINiPHg3zfGcNSt3434BrjL6VtSZurb2RfA40DA4VEqvFZep7AvqDx8KTIw/rcsGA0eFP1yS241Gc5jXVtnJaUtmhbEKH8Bos+mcBPc9Z2/x2pIfzisKPkM=
        write_files:
          - content: { get_file: ../scripts/setup-ssh.sh }
            owner: root:root
            permissions: '0774'
            path: /etc/setup-ssh.sh
          - content: { get_file: ../scripts/setup-wordpress.sh }
            owner: root:root
            permissions: '0774'
            path: /etc/setup-wordpress.sh
        runcmd:
          - bash -c /etc/setup-ssh.sh
          - bash -c /etc/setup-wordpress.sh
          # - sed -i'' -e "s/[\#]*Port\s.*/Port 1355/" /etc/ssh/sshd_config
          # - sed -i'' -e 's/[\#]*PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config
          # - sed -i'' -e '$aAllowUsers drew' /etc/ssh/sshd_config
          # - systemctl restart ssh


outputs:
  server_public_ip:
    description: public IP address of the deployed compute instance
    value: { get_attr: [server_floating_ip, floating_ip_address] }
  server_dmz_ip:
    description: private IP address on the dmz_network
    value: { get_attr: [server, networks, dmz_network, 0] }
  server_private_ip:
    description: private IP address on an private_network network only accessible through the firewall
    value: { get_attr: [server, networks, private_network, 0] }