#!/bin/sh

# Run after sourcing the OpenStack openrpc

cat <<EOF
{
    "OS_AUTH_URL": "$OS_AUTH_URL",
    "OS_INTERFACE": "$OS_INTERFACE",
    "OS_IDENTITY_API_VERSION": "$OS_IDENTITY_API_VERSION",
    "OS_PROJECT_ID": "$OS_PROJECT_ID",
    "OS_PROJECT_NAME": "$OS_PROJECT_NAME",
    "OS_USER_DOMAIN_NAME": "$OS_USER_DOMAIN_NAME",
    "OS_PROJECT_DOMAIN_ID": "$OS_PROJECT_DOMAIN_ID",
    "OS_USERNAME": "$OS_USERNAME",
    "OS_PASSWORD": "$OS_PASSWORD"
}
EOF