#cloud-config
package_update: true
packages:
  - bash-completion
users:
  - name: drew
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$rounds=4096$nQEeaHtrjiUlxOPi$LQlgi0XBR6u46AJFhWxsWBBK8YqHbGWYWkWnG.YhmdYkc/lMiAacMwQAbZ0W7MosLFexushHQpfa05eG7gsL/1
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCX3ZnnojSpqi1R7CWmP7uVFU2fEd2uS4PYQpWC23ScmDGP7KFHeTJfMc6eMaAhbxfIXx2CFdsIhP5U58BFLmAxkUIM8lGnHgh1uME/aOMZokZrDhYnw0eaamVOg0rdKD/uaTo87ASoxpf0XYnrqcrYhFIQodxjsCC8pCU5Egjh9QDgHsniJ5vWEkxZGPQ4SXIj4txh8uXMI0mh57BWJRK0zJIDzZCxubtrOpWoQnVvg/ZV+Thgy0P9m7e8OHbaM3U/7p4DBd1MZ95jNwjefMeD5hR46T35rkR9w/ebEIKhGjz0UB2yRUZPOPqBzVfixYA6gfd5c1AhjluCyCqhLEMd Generated-by-Nova
write_files:
  - path: /etc/ssh/sshd_config
    content: |
      Port 1355
      PermitRootLogin no
    append: true
  - path: /root/lemp-install.sh
    encoding: base64
    permissions: 700
    content: |-
      IyEvYmluL2Jhc2gKCnNldCAtZQpzb3VyY2UgYXV0aC9hbHRlcm5jbG91ZC5lbnYKCkRPTUFJTj0ieW91cl9kb21haW4iCgojIEluc3RhbGwgcGFja2FnZXMKc3VkbyBhcHQgdXBkYXRlCnN1ZG8gYXB0IGluc3RhbGwgLXkgbmdpbnggbWFyaWFkYi1zZXJ2ZXIgcGhwLWZwbSBwaHAtbXlzcWwKCiMgQ29uZmlndXJlIG1hcmlhZGIKc3VkbyBteXNxbF9zZWN1cmVfaW5zdGFsbGF0aW9uCm1hcmlhZGIgLXUgd3AtdXNlciAtcAoKIyBDb25maWd1cmUgbmdpbngKc3VkbyBta2RpciAvdmFyL3d3dy8kRE9NQUlOCnN1ZG8gY2hvd24gLVIgJFVTRVI6JFVTRVIgL3Zhci93d3cvJERPTUFJTgpzdWRvIHRvdWNoIC9ldGMvbmdpbngvc2l0ZXMtYXZhaWxhYmxlLyRET01BSU4KZWNobyAic2VydmVyIHsKICAgICAgICBsaXN0ZW4gODA7CiAgICAgICAgbGlzdGVuIFs6Ol06ODA7CgogICAgICAgIHJvb3QgL3Zhci93d3cveW91cl9kb21haW47CiAgICAgICAgaW5kZXggaW5kZXgucGhwIGluZGV4Lmh0bWwgaW5kZXguaHRtOwoKICAgICAgICBzZXJ2ZXJfbmFtZSB5b3VyX2RvbWFpbjsKCiAgICAgICAgbG9jYXRpb24gLyB7CiAgICAgICAgICAgIHRyeV9maWxlcyAkdXJpICR1cmkvID00MDQ7CiAgICAgICAgfQoKICAgICAgICBsb2NhdGlvbiB+IFwucGhwJCB7CiAgICAgICAgICAgIGluY2x1ZGUgc25pcHBldHMvZmFzdGNnaS1waHAuY29uZjsKICAgICAgICAgICAgZmFzdGNnaV9wYXNzIHVuaXg6L3Zhci9ydW4vcGhwL3BocDcuMy1mcG0uc29jazsKICAgICAgICB9CiAgICB9IiA+IC9ldGMvbmdpbngvc2l0ZXMtYXZhaWxhYmxlLyRET01BSU4Kc3VkbyBsbiAtcyAvZXRjL25naW54L3NpdGVzLWF2YWlsYWJsZS8kRE9NQUlOIC9ldGMvbmdpbngvc2l0ZXMtZW5hYmxlZC8Kc3VkbyBuZ2lueCAtdApzdWRvIHN5c3RlbWN0bCByZWxvYWQgbmdpbngKCiMgSW5zdGFsbCB3b3JkcHJlc3MKd2dldCBodHRwczovL3dvcmRwcmVzcy5vcmcvbGF0ZXN0LnppcA==
runcmd:
  - systemctl restart sshd
  - /root/lemp-install.sh
