# Created by trellis-cli v1.11.0
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  example.com:
    site_hosts:
    - canonical: example.com
      redirects:
      - www.example.com
    local_path: ../site
    branch: master
    repo: https://github.com/roots/bedrock
    repo_subtree_path: site
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: manual
      cert: ../../../../auth/doctor-ew.com.crt
      key:  ../../../../auth/doctor-ew.com.key
    cache:
      enabled: false
