apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f projects/nextcloud-testing/docker/docker-compose.yml -o projects/nextcloud-testing/kubernetes
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: nextcloud
  name: nextcloud
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: nextcloud
status:
  loadBalancer: {}
