extraLabels: {}

nameOverride: ""
fullnameOverride: ""
timeout: 3m

csi:
  attacher:
    image:
      repository: registry.k8s.io/sig-storage/csi-attacher
      tag: v4.2.0
      pullPolicy: IfNotPresent
    resources: {}
    extraArgs: {}
  provisioner:
    topology: "true"
    image:
      repository: registry.k8s.io/sig-storage/csi-provisioner
      tag: v3.4.1
      pullPolicy: IfNotPresent
    resources: {}
    extraArgs: {}
  snapshotter:
    image:
      repository: registry.k8s.io/sig-storage/csi-snapshotter
      tag: v6.2.1
      pullPolicy: IfNotPresent
    resources: {}
    extraArgs: {}
  resizer:
    image:
      repository: registry.k8s.io/sig-storage/csi-resizer
      tag: v1.7.0
      pullPolicy: IfNotPresent
    resources: {}
    extraArgs: {}
  livenessprobe:
    image:
      repository: registry.k8s.io/sig-storage/livenessprobe
      tag: v2.9.0
      pullPolicy: IfNotPresent
    failureThreshold: 5
    initialDelaySeconds: 10
    timeoutSeconds: 10
    periodSeconds: 60
    resources: {}
    extraArgs: {}
  nodeDriverRegistrar:
    image:
      repository: registry.k8s.io/sig-storage/csi-node-driver-registrar
      tag: v2.6.2
      pullPolicy: IfNotPresent
    resources: {}
    extraArgs: {}
  plugin:
    image:
      repository: registry.k8s.io/provider-os/cinder-csi-plugin
      pullPolicy: IfNotPresent
      tag:  # defaults to .Chart.AppVersion
    volumes:
      - name: cacert
        hostPath:
          path: /etc/cacert
    volumeMounts:
      - name: cacert
        mountPath: /etc/cacert
        readOnly: true
      - name: cloud-config
        mountPath: /etc/kubernetes
        readOnly: true
    nodePlugin:
      affinity: {}
      nodeSelector: {}
      tolerations:
        - operator: Exists
      kubeletDir: /var/lib/kubelet
    controllerPlugin:
      replicas: 1
      strategy:
        # RollingUpdate strategy replaces old pods with new ones gradually,
        # without incurring downtime.
        type: RollingUpdate
        rollingUpdate:
          # maxUnavailable is the maximum number of pods that can be
          # unavailable during the update process.
          maxUnavailable: 0
          # maxSurge is the maximum number of pods that can be
          # created over the desired number of pods.
          maxSurge: 1
      affinity: {}
      nodeSelector: {}
      tolerations: []
    resources: {}
    extraArgs: {}

# Log verbosity level.
# See https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md
# for description of individual verbosity levels.
logVerbosityLevel: 2

secret:
  enabled: true
  create: true
  filename: cloud.conf
  name: cinder-csi-cloud-config
  data:
    cloud.conf: |-
      [Global]
      auth-url=https://vpc2-console.cloud.alterncloud.com:5000
      application-credential-id=8b52e684710c41ceb236fccab716c6cf
      application-credential-secret=gry6Y49lvypYik1EpMDimdpvi1Gm9zri4mKBJQpAYizzL9ZQZP_V-Wpgmjt6rxh5zos2hBylq3dCaj2sHm6xWQ

      [LoadBalancer]
      use-octavia=true
      
  # ca-file=/etc/cacert/ca-bundle.crt
  # floating-network-id=b1d12129-bbfc-4482-a5d2-c20458459ddc
  # subnet-id=4e7309a5-50d3-46f1-bf37-2f2af80e3130

storageClass:
  enabled: true
  delete:
    isDefault: false
    allowVolumeExpansion: true
  retain:
    isDefault: false
    allowVolumeExpansion: true
# any kind of custom StorageClasses
  custom: |-
    ---
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: csi-sc-cinder
      annotations:
        storageclass.kubernetes.io/is-default-class: "true"
    provisioner: cinder.csi.openstack.org
    parameters:
      availability: nova
      allowVolumeExpansion: "true"
      volumeBindingMode: Immediate
    ---
#     apiVersion: snapshot.storage.k8s.io/v1
#     kind: VolumeSnapshotClass
#     metadata:
#       name: csi-cinder-snapclass
#     driver: cinder.csi.openstack.org
#     deletionPolicy: Delete

# You may set ID of the cluster where openstack-cinder-csi is deployed. This value will be appended
# to volume metadata in newly provisioned volumes as `cinder.csi.openstack.org/cluster=<cluster ID>`.
clusterID: "kubernetes"

priorityClassName: ""

imagePullSecrets: []
# - name: my-imagepull-secret