version: "3"

services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      # - SERVERURL=  #optional
      - SERVERPORT=51820 #optional
      - PEERS=5 #optional
      - PEERDNS=1.1.1.1,1.0.0.1 #optional
      # - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
      - PERSISTENTKEEPALIVE_PEERS= #optional
      - LOG_CONFS=true #optional
    volumes:
      - ./wireguard:/config
      - /lib/modules:/lib/modules #optional
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  # wireguard-ui:
  #   image: ngoduykhanh/wireguard-ui:latest
  #   container_name: wireguard-ui
  #   depends_on:
  #     - wireguard
  #   cap_add:
  #     - NET_ADMIN
  #   # use the network of the 'wireguard' service. this enables to show active clients in the status page
  #   network_mode: service:swag
  #   environment:
  #     - SENDGRID_API_KEY
  #     - EMAIL_FROM_ADDRESS
  #     - EMAIL_FROM_NAME
  #     - SESSION_SECRET
  #     - WGUI_USERNAME=admin
  #     - WGUI_PASSWORD=
  #     - WG_CONF_TEMPLATE
  #     - WGUI_MANAGE_START=true
  #     - WGUI_MANAGE_RESTART=true
  #   logging:
  #     driver: json-file
  #     options:
  #       max-size: 50m
  #   volumes:
  #     - ./wireguard-ui-db:/app/db
  #     - ./wireguard-ui:/etc/wireguard
