services: 
  nginx:
    container_name: nginx
    image: nginx:latest
    network_mode: host
    restart: unless-stopped
    volumes:
      - /config/nginx/templates:/etc/nginx/templates/
      - /config/nginx/site-confs:/etc/nginx/conf.d/
      - /config/nginx/ssl:/etc/nginx/ssl/
